### ISSUE TITLE
panics in workspace members are not matched

### ISSUE THREAD

**Issue by colin-kiegel** [AtomBuild/atom-build-cargo#84]
Cargo introduced [support for workspaces](https://github.com/rust-lang/rfcs/blob/master/text/1525-cargo-workspace.md) a while ago.

Say we have a virtual manifest `foo/Cargo.toml`
```toml
[workspace]
members = ["child"]
```

And a child crate with `foo/child/Cargo.toml`
```toml
[package]
workspace = ".."
# .. the usual
```

Now say that the child crate has a test that panics `foo/child/tests/bar.rs`
```rust
#[test]
fn todo() {
    unimplemented!()
}
```

Then `atom-build-cargo` will be able to build/test the crate and the panic is visible in the output console. **However no notification about a panic appears**. If the test is moved to the top level crate `foo` of the workspace, the notification would appear.

It would be nice if those panics would also produce notifications for child crates. :-)

<details>
<summary>cargo test output</summary>
<pre>
Running /home/colin/projects/rust/foo/target/debug/deps/bar-45006a5d7ab180f7
 
running 1 test
test todo ... FAILED
 
failures:
 
---- todo stdout ----
        thread 'todo' panicked at 'not yet implemented', tests/bar.rs:55
stack backtrace:
   1:     0x55bd152639bc - std::sys::imp::backtrace::tracing::imp::write::hf33ae72d0baa11ed
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:     0x55bd15266b0e - std::panicking::default_hook::{{closure}}::h59672b733cc6a455
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:351
   3:     0x55bd152666b3 - std::panicking::default_hook::h1670459d2f3f8843
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:361
   4:     0x55bd15266fab - std::panicking::rust_panic_with_hook::hcf0ddb069e7beee7
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:555
   5:     0x55bd15224933 - std::panicking::begin_panic::ha6a247592b029c34
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:517
   6:     0x55bd15226562 - custom_default::todo::h0d4eca0c1e06ce92
                        at /home/colin/projects/rust/derive-builder/derive_builder/tests/custom_default.rs:55
   7:     0x55bd152351be - <F as test::FnBox<T>>::call_box::he0ddef732487ab41

                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libtest/lib.rs:1366
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libtest/lib.rs:140
   8:     0x55bd1526deba - __rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libpanic_unwind/lib.rs:98
   9:     0x55bd152295aa - std::panicking::try::do_call::h4652d5e10f648844
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:436
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panic.rs:361
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libtest/lib.rs:1311
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panic.rs:296
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:460
  10:     0x55bd1526deba - __rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libpanic_unwind/lib.rs:98
  11:     0x55bd152301d6 - <F as alloc::boxed::FnBox<A>>::call_box::h274e3783c3771bc8
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:436
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panic.rs:361
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/thread/mod.rs:357
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/liballoc/boxed.rs:614
  12:     0x55bd15265e14 - std::sys::imp::thread::Thread::new::thread_start::he668872ac11287ba
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/liballoc/boxed.rs:624
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/sys_common/thread.rs:21
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/sys/unix/thread.rs:84
  13:     0x7fe3529f06b9 - start_thread
  14:     0x7fe35251082c - clone
  15:                0x0 - <unknown>
 
 
failures:
    todo
 
test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured
 
error: test failed
</pre>
</details>

**Comment by colin-kiegel** [comment]
Ok, I have to correct this: workspaces do indeed work fine. The problem I was experiencing is not related to workspaces but to newlines in a panic message. I will open a separate issue.
